// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EarlyXrm.PacHelper
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPacHelperPackageString = "5a74d077-a176-4406-a5ca-48f36ef1d0f7";
        public static Guid guidPacHelperPackage = new Guid(guidPacHelperPackageString);

        public const string guidPacHelperPackageCmdSetString = "a3659495-15ca-4b04-a1fb-40dabda01a35";
        public static Guid guidPacHelperPackageCmdSet = new Guid(guidPacHelperPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int PacMenu = 0x1040;
        public const int PacMenuGroup = 0x1020;
        public const int ToolsMenu = 0x1021;
        public const int PacOrgSelect = 0x0101;
        public const int PacSolutionSync = 0x1022;
        public const int PacSolutionImport = 0x1023;
        public const int PacSolutionClone = 0x1028;
        public const int PacDataSync = 0x1024;
        public const int PacDataImport = 0x1025;
        public const int PacPagesSync = 0x1026;
        public const int PacPagesImport = 0x1027;
    }
}