// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EarlyXrm.PacHelper
{
    internal sealed partial class Vsix
    {
        public const string Id = "EarlyXrm.PacHelper.af7a04ec-48a5-42f8-9642-ee70f3f209ed";
        public const string Name = "EarlyXrm.PacHelper";
        public const string Description = @"Helper for Power Platform CLIH";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Andy Berman";
        public const string Tags = "";
    }
}
